### ISSUE TITLE
Android 无法安装最新破解版

### ISSUE THREAD

**Issue by luckyjinx** [rartv/EmbyPublic#3]
提示 应用未安装 需要核心破解吗？

**Comment by rartv** [comment]
如果装了其他人破解的版本，需要先卸载

**Comment by luckyjinx** [comment]
> 如果装了其他人破解的版本，需要先卸载

没有 甚至官方版本都没有安装 安卓11 Pixel experience 设备一加7t

**Comment by rartv** [comment]
手机哦，这个项目发布的最新版是安卓TV系统的 App，不是安卓手机系统的。安卓版不需要破解，官网或者 Google Play 下载后直接使用。
