### ISSUE TITLE
Android TV 2.0.33g 中文搜索不行

### ISSUE THREAD

**Issue by uniqueque** [rartv/EmbyPublic#4]
这个版本的中文搜索好像不行，英文可以。
在电视上搜索不行，安卓模拟器（网易mumu）上试了也不行

**Comment by rartv** [comment]
我这边测试了

1. 小米电视 (国产魔改安卓TV6.0)
2. 火棒 (国外魔改安卓TV最新版)
3. Miboxs 盒子(原生安卓TV9.0)
4. MeCool KM2 盒子 (原生安卓TV10.0)

中文搜索均没有问题

**Comment by uniqueque** [comment]
好的，感谢，这个版本挺不错的

**Comment by spacex-3** [comment]
有同样的问题。。。为啥不能搜索中文呢，网页版的emby都能正常搜索诶

用的是开心版的emby，然后梯子也没开呢
